export const cookingWords = [
    'bread', 'aroma', 'bagel', 'beer',
    'beans', 'cake', 'butter', 'candy', 'chili',
    'caramel', 'burger', 'chocolate', 'mayonnaise', 'broth',
    'drink', 'croissant', 'kitchen',
    'cheese', 'cookie', 'caviar', 'muffin', 'margarine',
    'hamburger', 'juice', 'crumble', 'biscuit', 'oil',
    'meat', 'syrup', 'pizza',
    'eggs', 'ketchup', 'plate', 'food', 'flour',
    'soda', 'omelette', 'entree', 'cocoa', 'recipe',
    'cuisine', 'ice', 'fish',
    'steak', 'cream', 'cider', 'skillet',
    'wheat', 'pasta', 'salad', 'filet', 'raclette',
    'seasoning', 'dessert', 'stew', 'taste',
    'liquor', 'sandwich', 'coffee', 'milk', 'mousse',
    'soup', 'mushroom', 'pie', 'curd', 'mayo',
    'water', 'wok', 'olive',
    'waffle', 'pudding', 'rice', 'toast', 'spice',
    'pastry', 'grill', 'marinade', 'soy', 'vinegar',
    'tea', 'yogurt', 'sauce', 'poutine',
    'wine', 'yeast'
] as const