export const reptileWords = ["alligator",
    "chameleon",
    "cobra",
    "copperhead",
    "crocodile",
    "gecko",
    "iguana",
    "kingsnake",
    "lizard",
    "reptile",
    "seaturtle",
    "skink",
    "snake",
    "tortoise",
    "turtle",
    "viper"] as const