interface ILS {
    unlockedLevels: { [key: string]: boolean };
    completedLevels: { [key: string]: boolean };
}

const everyLevel = {
    "Food I": true,
    "Clothing I": true,
    "Geography I": true,
    "Ocean I": true,
    "Flowers I": true,
    "Food II": true,
    "Ocean II": true,
    "Dogs I": true,
    "Pirates I": true,
    "Autumn I": true,
    "Clothing II": true,
    "Autumn II": true,
    "Devices I": true,
    "Furniture I": true,
    "Vehicles I": true,
    "Farm I": true,
    "Autumn III": true,
    "Instruments I": true,
    "Furniture II": true,
    "Flowers II": true,
    "Farm II": true,
    "Food III": true,
    "Insects I": true,
    "Vehicles II": true,
    "Clothing III": true,
    "Vehicles III": true,
    "Sports I": true,
    "Autumn IV": true,
    "Dogs II": true,
    "Plants I": true,
    "Shapes I": true,
    "Desserts I": true,
    "Sports II": true,
    "Plants II": true,
    "Farm III": true,
    "Plants III": true,
    "Instruments II": true,
    "Christmas I": true,
    "Shapes II": true,
    "Pirates II": true,
    "Desserts II": true,
    "Vehicles IV": true,
    "Reptiles I": true,
    "Dogs III": true,
    "Desserts III": true,
    "Vehicles V": true,
    "Flowers III": true,
    "Furniture III": true,
    "Furniture IV": true,
    "Insects II": true,
    "Shapes III": true,
    "Desserts IV": true,
    "Geography II": true,
    "Pirates III": true,
    "Reptiles II": true,
    "Shapes IV": true,
    "Geography III": true,
    "Plants IV": true,
    "Autumn V": true,
    "Insects III": true,
    "Desserts V": true,
    "Sports III": true,
    "Flowers IV": true,
    "Desserts VI": true,
    "Geography IV": true,
    "Instruments III": true,
    "Plants V": true,
    "Sports IV": true,
    "Geography V": true,
    "Vehicles VI": true,
    "Reptiles III": true,
    "Devices II": true,
    "Christmas II": true,
    "Desserts VII": true,
    "Shapes V": true,
    "Pirates IV": true,
    "Dogs IV": true,
    "Vehicles VII": true,
    "Geography VI": true,
    "Instruments IV": true,
    "Pirates V": true,
    "Insects IV": true,
    "Vehicles VIII": true,
    "Geography VII": true,
    "Reptiles IV": true,
    "Insects V": true,
    "Art I": true,
    "Flowers V": true,
    "Sports V": true,
    "Christmas III": true,
    "Vehicles IX": true,
    "Reptiles V": true,
    "Insects VI": true,
    "Autumn VI": true,
    "Instruments V": true,
    "Sports VI": true,
    "Desserts VIII": true,
    "Geography VIII": true,
    "Insects VII": true,
    "Pirates VI": true,
    "Art II": true,
    "Food IV": true,
    "Furniture V": true,
    "Autumn VII": true,
    "Plants VI": true,
    "Dogs V": true,
    "Autumn VIII": true,
    "Christmas IV": true,
    "Shapes VI": true,
    "Geography IX": true,
    "Food V": true,
    "Furniture VI": true,
    "Furniture VII": true,
    "Autumn IX": true,
    "Furniture VIII": true,
    "Desserts IX": true,
    "Sports VII": true,
    "Plants VII": true,
    "Farm IV": true,
    "Instruments VI": true,
    "Farm V": true,
    "Devices III": true,
    "Sports VIII": true,
    "Desserts X": true,
    "Furniture IX": true,
    "Plants VIII": true,
    "Autumn X": true,
    "Geography X": true,
    "Clothing IV": true,
    "Farm VI": true,
    "Farm VII": true,
    "Insects VIII": true,
    "Geography XI": true,
    "Furniture X": true,
    "Farm VIII": true,
    "Pirates VII": true,
    "Insects IX": true,
    "Shapes VII": true,
    "Desserts XI": true,
    "Devices IV": true,
    "Shapes VIII": true,
    "Instruments VII": true,
    "Sports IX": true,
    "Farm IX": true,
    "Pirates VIII": true,
    "Plants IX": true,
    "Insects X": true,
    "Ocean III": true,
    "Shapes IX": true,
    "Pirates IX": true,
    "Dogs VI": true,
    "Devices V": true,
    "Farm X": true,
    "Reptiles VI": true,
    "Devices VI": true,
    "Christmas V": true,
    "Flowers VI": true,
    "Ocean IV": true,
    "Clothing V": true,
    "Flowers VII": true,
    "Reptiles VII": true,
    "Shapes X": true,
    "Instruments VIII": true,
    "Reptiles VIII": true,
    "Shapes XI": true,
    "Pirates X": true
}

const everyLS: ILS = {
    unlockedLevels: everyLevel,
    completedLevels: everyLevel,
}

export const defaultLS: ILS = {
    unlockedLevels: {
        "Food I": true
    },
    completedLevels: {

    }
};

const disableLS = false;
const doEveryLS = true;

const ls = doEveryLS ? JSON.stringify(everyLS) : (!disableLS && localStorage.getItem("LS_wordfind")) || JSON.stringify(defaultLS);

const LS: ILS = JSON.parse(ls);

export const getLS = (key: keyof ILS) => LS[key];
export const setLS = (key: keyof ILS, value: ILS[keyof ILS]) => {
    LS[key] = value;
    localStorage.setItem("LS_wordfind", JSON.stringify(LS));
}