interface ILS {
    unlockedLevels: { [key: string]: boolean };
    completedLevels: { [key: string]: boolean };
}

const everyLevel = {
    "Food I": true,
    "Vehicles I": true,
    "Autumn I": true,
    "Ocean I": true,
    "Food II": true,
    "Clothing I": true,
    "Sports I": true,
    "Autumn II": true,
    "Ocean II": true,
    "Vehicles II": true,
    "Autumn III": true,
    "Reptiles I": true,
    "Geography I": true,
    "Flowers I": true,
    "Plants I": true,
    "Flowers II": true,
    "Sports II": true,
    "Vehicles III": true,
    "Furniture I": true,
    "Dogs I": true,
    "Plants II": true,
    "Instruments I": true,
    "Instruments II": true,
    "Shapes I": true,
    "Sports III": true,
    "Instruments III": true,
    "Dogs II": true,
    "Instruments IV": true,
    "Flowers III": true,
    "Autumn IV": true,
    "Art I": true,
    "Desserts I": true,
    "Clothing II": true,
    "Flowers IV": true,
    "Instruments V": true,
    "Ocean III": true,
    "Art II": true,
    "Sports IV": true,
    "Desserts II": true,
    "Vehicles IV": true,
    "Shapes II": true,
    "Furniture II": true,
    "Vehicles V": true,
    "Devices I": true,
    "Desserts III": true,
    "Farm I": true,
    "Dogs III": true,
    "Vehicles VI": true,
    "Art III": true,
    "Pirates I": true,
    "Vehicles VII": true,
    "Vehicles VIII": true,
    "Art IV": true,
    "Autumn V": true,
    "Flowers V": true,
    "Reptiles II": true,
    "Insects I": true,
    "Instruments VI": true,
    "Pirates II": true,
    "Autumn VI": true,
    "Reptiles III": true,
    "Food III": true,
    "Food IV": true,
    "Vehicles IX": true,
    "Clothing III": true,
    "Shapes III": true,
    "Flowers VI": true,
    "Plants III": true,
    "Insects II": true,
    "Reptiles IV": true,
    "Desserts IV": true,
    "Farm II": true,
    "Reptiles V": true,
    "Clothing IV": true,
    "Food V": true,
    "Art V": true,
    "Food VI": true,
    "Art VI": true,
    "Farm III": true,
    "Ocean IV": true,
    "Reptiles VI": true,
    "Autumn VII": true,
    "Geography II": true,
    "Desserts V": true,
    "Dogs IV": true,
    "Plants IV": true,
    "Pirates III": true,
    "Insects III": true,
    "Instruments VII": true,
    "Shapes IV": true,
    "Dogs V": true,
    "Flowers VII": true,
    "Reptiles VII": true,
    "Christmas I": true,
    "Reptiles VIII": true,
    "Reptiles IX": true,
    "Reptiles X": true,
    "Reptiles XI": true,
    "Devices II": true,
    "Geography III": true,
    "Christmas II": true,
    "Pirates IV": true,
    "Reptiles XII": true,
    "Vehicles X": true,
    "Food VII": true,
    "Plants V": true,
    "Art VII": true,
    "Sports V": true,
    "Dogs VI": true,
    "Dogs VII": true,
    "Devices III": true,
    "Farm IV": true,
    "Ocean V": true,
    "Vehicles XI": true,
    "Dogs VIII": true,
    "Geography IV": true,
    "Pirates V": true,
    "Clothing V": true,
    "Reptiles XIII": true,
    "Clothing VI": true,
    "Devices IV": true,
    "Insects IV": true,
    "Food VIII": true,
    "Dogs IX": true,
    "Shapes V": true,
    "Instruments VIII": true,
    "Clothing VII": true,
    "Autumn VIII": true,
    "Plants VI": true,
    "Autumn IX": true,
    "Shapes VI": true,
    "Ocean VI": true,
    "Autumn X": true,
    "Shapes VII": true,
    "Art VIII": true,
    "Flowers VIII": true,
    "Desserts VI": true,
    "Insects V": true,
    "Clothing VIII": true,
    "Devices V": true,
    "Pirates VI": true,
    "Ocean VII": true,
    "Geography V": true,
    "Reptiles XIV": true,
    "Devices VI": true,
    "Reptiles XV": true,
    "Farm V": true,
    "Devices VII": true,
    "Vehicles XII": true,
    "Geography VI": true,
    "Desserts VII": true,
    "Plants VII": true,
    "Ocean VIII": true,
    "Autumn XI": true,
    "Food IX": true,
    "Clothing IX": true,
    "Reptiles XVI": true,
    "Reptiles XVII": true,
    "Farm VI": true,
    "Art IX": true,
    "Pirates VII": true,
    "Sports VI": true,
    "Vehicles XIII": true,
    "Clothing X": true,
    "Desserts VIII": true,
    "Sports VII": true,
}

const everyLS: ILS = {
    unlockedLevels: everyLevel,
    completedLevels: everyLevel,
}

export const defaultLS: ILS = {
    unlockedLevels: {
        "Food I": true
    },
    completedLevels: {

    }
};

const disableLS = false;
const doEveryLS = true;

const ls = doEveryLS ? JSON.stringify(everyLS) : (!disableLS && localStorage.getItem("LS_wordfind")) || JSON.stringify(defaultLS);

const LS: ILS = JSON.parse(ls);

export const getLS = (key: keyof ILS) => LS[key];
export const setLS = (key: keyof ILS, value: ILS[keyof ILS]) => {
    LS[key] = value;
    localStorage.setItem("LS_wordfind", JSON.stringify(LS));
}